services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=veiculos
      - POSTGRES_PASSWORD=veiculos
      - POSTGRES_DB=veiculos
    ports:
      - "5432:5432"
    volumes:
      - ${PWD}/src/main/resources/migration/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - localnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d video_processor -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - localnet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  localnet:
    external: true