services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ${PWD}/src/main/resources/migration/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - localnet
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-admin} -d ${DB_NAME:-veiculos_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning
    networks:
      - localnet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: ghcr.io/hfantin/veiculos:0.1.0
    environment:
      - OKTA_OAUTH2_CLIENT_ID=${AUTH0_CLIENT_ID}
      - OKTA_OAUTH2_CLIENT_SECRET=${AUTH0_CLIENT_SECRET}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/veiculos_db
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_MAIL_USERNAME=${EMAIL_SENDER_FROM}
      - SPRING_MAIL_PASSWORD=${EMAIL_SENDER_PASSWORD}
      - MERCADOPAGO_ACCESS_TOKEN=${MERCADO_LIVRE_PASS}
      - MERCADOPAGO_BASE_URL=https://api.mercadopago.com
    ports:
      - "8080:8080"
    networks:
      - localnet
    depends_on:
      - db

networks:
  localnet:
    external: true
