name: Build, Tag and Release Spring Boot App

on:
  push:
    branches:
      - main

permissions:
  contents: write   # ✅ allows pushing tags and creating releases
  packages: write

jobs:
  build-tag-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to create tags and check existing ones

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Extract version from pom.xml
        id: extract_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Validate semantic version
        run: |
          VERSION=${{ steps.extract_version.outputs.version }}
          if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ Version $VERSION is not a valid closed semantic version (x.y.z)"
            exit 1
          fi

      - name: Check if tag already exists
        run: |
          VERSION=${{ steps.extract_version.outputs.version }}
          if git rev-parse "refs/tags/$VERSION" >/dev/null 2>&1; then
            echo "❌ Tag $VERSION already exists!"
            exit 1
          fi

      - name: Build JAR
        run: mvn clean package -DskipTests

      - name: Create git tag
        run: |
          VERSION=${{ steps.extract_version.outputs.version }}
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git tag "$VERSION"
          git push origin "$VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract_version.outputs.version }}
          name: Release ${{ steps.extract_version.outputs.version }}
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}